language: node_js
node_js:
  - "0.10"
before_script:
  - "IOJS_VERSION=v1.0.1; wget https://iojs.org/dist/${IOJS_VERSION}/iojs-${IOJS_VERSION}-linux-x64.tar.xz && tar xvfJ iojs-${IOJS_VERSION}-linux-x64.tar.xz && sudo mv iojs-${IOJS_VERSION}-linux-x64/bin/iojs /usr/local/bin"
script:
  - "iojs -v"
